### ISSUE TITLE
`npm run watch` doesn't exit on SIGINT

### ISSUE THREAD

**Issue by Akallabet** [fastify/demo#23]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x.x

### Plugin version

4.x.x

### Node.js version

22.8.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.6.1 

### Description

`npm run watch` leaves the node process running upon SIGINT (control + C in my case).

![Screenshot 2024-09-09 at 11 51 51](https://github.com/user-attachments/assets/c215a82b-a629-47d1-83c4-f31c713005cd)

### Expected Behavior

`npm run watch` to exit gracefully upon SIGINT

**Comment by Akallabet** [comment]
Closing as I am not running node@22.x.x

**Comment by Akallabet** [comment]
Reopening as it still happens with node@22.8.0

**Comment by wizmea** [comment]
Upgrate to v22.14.0 fixed the issue for fastify v5
