### ISSUE TITLE
Tests won't run due to esm or ts related issue

### ISSUE THREAD

**Issue by berkerdemirer** [fastify/demo#32]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5

### Node.js version

22

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

latest

### Description

Tests are not running. 

Tried to run the tests but I guess there is something off with test runner and typescript. If I use the default runner then it cannot compile the .ts extension. if I use tsx then i get something like: 

`@fastify/autoload cannot import plugin at '/Users/berkerdemirer/git/sightsnap-server/src/plugins/external/clerk.ts'. To fix this error compile TypeScript to JavaScript or use 'ts-node' to run your app.`

any idea how to solve this?

### Expected Behavior

Tests should run

**Comment by jean-michelet** [comment]
It looks like you added an external plugin, did you edit anything else?

Can you give the diff between `main` on this repo and you current branch plz?

A reproduction repository could help too.

**Comment by berkerdemirer** [comment]
I actually tested out within the demo repo as well. I think the issue is related with the test runner. I am using webstorm atm and just try to invoke single test run through the IDE. Can't get it to work with either ts-node or tsx. But, i guess that's not really related with the repo.

![image](https://github.com/user-attachments/assets/43c9370c-48e3-4cfc-b02a-8f658773f65c)

**Comment by jean-michelet** [comment]
Regarding the autoloader error, does it work if you implement this: https://github.com/fastify/fastify-autoload?tab=readme-ov-file#override-typescript-detection-using-an-environment-variable

The autoloader should support `tsx` btw: https://github.com/fastify/fastify-autoload/blob/master/scripts/unit-typescript-tsx.js

**Comment by jean-michelet** [comment]
What is the state of this issue?

**Comment by jean-michelet** [comment]
Closed due to non-activity.
