### ISSUE TITLE
Create a endpoint to delete a task image

### ISSUE THREAD

**Issue by jean-michelet** [fastify/demo#37]
Currently we allow users to upload images, but not to delete them.

**Comment by strifee0903** [comment]
@jean-michelet Hi can you assign this to me ?

**Comment by jean-michelet** [comment]
Hi!

Go ahead ;)

**Comment by climba03003** [comment]
> Hi can you assign this to me ?

We do not assign the issue to anyone. If you are interested in this issue, you can fork this repository and send a PR for review.

**Comment by jean-michelet** [comment]
@strifee0903 
A  lot of people want to be assigned an issue but end up never pushing a PR or give up following the first feedbacks. We don't want to discourage people from taking an issue, this is why we usually don't assign issues.

**Comment by Turn0xx** [comment]
@jean-michelet Hi, i wan't to contribute, 

It's gonna be my first issue, what should i do after implementing feat ?
