### ISSUE TITLE
Missing build in the CI workflow file

### ISSUE THREAD

**Issue by melroy89** [fastify/demo#40]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I would like to see a `build` job that does only a production build: `npm run build`.

And I would rename the current "build" to "test": https://github.com/fastify/demo/blob/main/.github/workflows/ci.yml#L19

### Motivation

Missing a CI/CD build.. And what you called build today, is actually a test.

**Comment by melroy89** [comment]
PR created: https://github.com/fastify/demo/pull/41

**Comment by jean-michelet** [comment]
Thanks @melroy89!
