### ISSUE TITLE
Using static security analysis tool?

### ISSUE THREAD

**Issue by jean-michelet** [fastify/demo#42]
Maybe we should use [Snyk](https://snyk.io/) or another tool to look at the source code during CI (and to run locally).

**Comment by mcollina** [comment]
Agreed.

**Comment by fernan-x** [comment]
Do you already use another security analysis tool within the ecosystem ?

You mention [Snyk](https://snyk.io/), but there is also [OWASP Dependency-Check](https://jeremylong.github.io/DependencyCheck/) or [Sonar Cube community edition](https://www.sonarsource.com/open-source-editions/sonarqube-community-edition/).

I'll be happy to help integrate one of them. Or help to dig into the differences between them to help taking a decision.

**Comment by jean-michelet** [comment]
> Or help to dig into the differences between them to help taking a decision.

Go ahead 👍 

Checking dependencies with vulnerabilities is good, detect insecure patterns trough static code analysis is good too.

**Comment by lirantal** [comment]
Jumping in to clarify that Snyk scans both dependencies as well as first-party code (static analysis)

**Comment by gurgunday** [comment]
> Jumping in to clarify that Snyk scans both dependencies as well as first-party code (static analysis)

Nice!

**Comment by jean-michelet** [comment]
Do you want to work integrating Snyk @fernan-x?

**Comment by fernan-x** [comment]
Sure, I have some free time tomorrow.

**Comment by nvuillam** [comment]
You should have a look at megalinter :)

https://megalinter.io/latest/

100% free and open-source :)
