### ISSUE TITLE
Incorrect Documentation Link in Rate Limit Plugin

### ISSUE THREAD

**Issue by yudatadei** [fastify/demo#66]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

https://github.com/fastify/demo/blob/b18bd1aae9e1baf6e8eeae04eef36002e8b3a8f8/src/plugins/external/rate-limit.ts#L14

### Proposed Change
Replace the link with the correct GitHub repository link for the rate limit plugin:
`@link https://github.com/fastify/fastify-rate-limit`

### Additional Context
The current link directs to the Helmet plugin instead of the Rate Limit plugin, which could mislead developers looking for documentation.

**Comment by jean-michelet** [comment]
Thx, do you want to push a PR?

**Comment by yudatadei** [comment]
I created one here #67

**Comment by jean-michelet** [comment]
Thx, merged
