### ISSUE TITLE
Add description to about section

### ISSUE THREAD

**Issue by melroy89** [fastify/demo#69]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

@jean-michelet Maybe you could add a simple description and some additional GitHub topics to the repository about section? The additional topics could make this repository better findable in GitHub and outside of github actually as well.

This can be found (and edited by a gear icon I don't have) in the right top of the repository main project page:

![image](https://github.com/user-attachments/assets/881d4834-493f-4b83-9020-9aad5935f3a6)
 
 https://github.com/fastify/demo

**Comment by jean-michelet** [comment]
I added one, tell me if you have suggestions for a better description or topics.

**Comment by melroy89** [comment]
Description is perfect now. Thanks.

Topics could be extended with maybe: typescript, nodejs, demo, example, best-practices, npm,.. Just thinking out loud now. Maybe you have more. Right? The more the better.

**Comment by jean-michelet** [comment]
OK, I keep the issue if other people have feedback.

**Comment by melroy89** [comment]
Nah. It's fine. Closing.
